# this yaml is compatible with 0.9 only
Containers:
  Wordpress:
    Scheduler: random
    Config:
      Image: "wordpress:latest"
      Env:
        WORDPRESS_DB_HOST: 172.17.42.1
        WORDPRESS_DB_PASSWORD: letmein
      Ports:
        - HostPort: 80
          ContainerProtocol: tcp
          ContainerPort: 80
    Instances:
      Min: 1
      Max: 1
      Default: 1
  DB:
    Scheduler: random
    Config:
      Image: "mariadb:latest"
      Env:
        MYSQL_ROOT_PASSWORD: letmein
      Ports:
        - HostPort: 3306
          ContainerProtocol: tcp
          ContainerPort: 3306
    Instances:
      Min: 1
      Max: 1
      Default: 1
